### ISSUE TITLE
Add a SignatureBasedPaymaster contract

### ISSUE THREAD

**Issue by hoshiyari420** [matter-labs/paymaster-examples#23]
## Paymaster Description
**Objective**: Implement a`SignatureBasedPaymaster` contract that covers gas fees for users based on valid signature provided by the signer of the paymaster contract. 

## Rationale
1. **Enhanced user flexibility** : Current gated examples `Allowlist`,`ERC20Fixed`,`ERC721Gated` require owner of the paymaster to perform a certain type of on-chain transactions such as `setBatchAllowance() in Allowlist`, `Transferring ERC20 token to user`, `Transferring ERC721 token to user` etc. However, SignatureBasedPaymaster eliminates the necessity for pre-transaction and post-transaction requirements, thus making it more flexible.
 
2. **Efficient short term use** : New users onboarding without on-chain transactions from owner providing a **one-time** speedy and hassle-free process. 
 
3. **Secure personalised paymasters** : A personalised paymaster that takes care of gas fees of all the user's related addresses with simple off-chain signatures. An application can be build over this use-case; thus expanding mainstream paymaster services. 

#### Functionality:
- This paymaster contract shall validate based on the signature provided through `innerInputs` whether or not the user's transaction shall be allowed to proceed or not. 
- The signer shall have authority to ensure signature is only valid upto particular timestamp. 
- The signature shall be EIP712 compliance which is signed on values like `(user address, last timestamp, nonces)`. 
- Users are required to provide certain inputs such as signature and last timestamp as `innerInputs` in paymaster params. 
- The paymaster will then check signature based on `transaction.from`, `block.timestamp` and `nonces` to ensure only valid users are allowed to use paymaster. 

#### Security Considerations:
- Paymaster should use nonce for every user in validating signatures which increments on every successful transactions.
- Paymaster should check expiry timestamp of signatures. 
- Paymaster should validate signatures based on `transaction.from` to ensure correct user has sent transaction. 
- Paymaster should revert if recovered signer does not match or signature expires. 
- Owner can update the paymaster signer.
- Owner should be able to cancel any user's nonce. 
- EIP712 compliance signatures support. 
- Use of battle-tested standard libraries for ECDSA signature verification (Openzeppelin) 

## Are you willing to write the paymaster contract?
 Yes. Completed below deliverable tasks at [PR-22](https://github.com/matter-labs/paymaster-examples/pull/22):
- [X] Add SignatureBasedPaymaster contract 
- [X] Add unit testing, deploy scripts
- [X] Update readme.
- [ ] Update UI (needs more discussion)

Sample deployment on [mainnet](https://explorer.zksync.io/address/0x8345EC9324cDd5312b4760A718B684be3d854493)

**Comment by MexicanAce** [comment]
Completed and accept the PR. Thank you for your contribution @hoshiyari420 🥳🖖!!
